### PR TITLE
Fix showing review transaction on cred deployment

### LINKED ISSUE #8: Shows "Review transaction" when signing new credential
**Task description**
When making new account credentials, the Ledger says "Review Transaction", and since it is technically not a transaction, it should say something like “Review Details” or “Review Credential”.

### PR DESCRIPTION
**Pull request by shjortConcordium**
## Purpose

Currently signing credentials for credential deployment is called a transaction in the UI.
`Review Transaction`, `Sign Transaction` and `Decline to sign Transaction`.
This PR replaces `transaction` with `details`.

Fixes #8.

## Changes

Changes some UI elements in SignCredentialDeployment, to replace `transaction` with `details` in credential deployment only.
Changes credential_deployment test to allow sending credential from new or existing accounts.

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [ ] (If necessary) I have updated the CHANGELOG.

### CODE REVIEW

File: rust_tests/src/bin/credential_deployment.rs [hunk 1]
```diff
@@ -169,33 +181,28 @@ fn main() {
...
+        if new_account {
+            // Send transaction expiry (new account)
+            hex::decode("00000000006040F27E").unwrap()
+        } else {
+            // Send account address (exisisting account)
+            let account_address_base58 = "3C8N65hBwc2cNtJkGmVyGeWYxhZ6R3X77mLWTwAKsnAnyworTq";
+            let mut account_address_bytes = hex::decode("01").unwrap();
+            let mut account_address = account_address_base58.from_base58check().unwrap().1;
+            account_address_bytes.append(&mut account_address);
+            account_address_bytes
```
Comment (orhoj) [inline rust_tests/src/bin/credential_deployment.rs:194]: Delete this line.

File: src/signCredentialDeployment.c [hunk 2]
```diff
@@ -26,10 +26,18 @@ UX_STEP_CB(
     sendSuccessNoIdle(),
     {
       "Review",
-      "transaction"
+      "details"
     });
 UX_STEP_CB(
-    ux_credential_deployment_initial_flow_1_step,
+    ux_update_credentials_initial_flow_0_step,
```
Comment (orhoj) [inline src/signCredentialDeployment.c:32]: You should remove this component and use the shared `ux_sign_flow_shared_review` instead which does not have a callback function.

File: src/signCredentialDeployment.c [hunk 3]
```diff
@@ -137,14 +145,19 @@ UX_STEP_CB(
...
-UX_FLOW(ux_sign_credential_deployment,
+
+UX_FLOW(ux_sign_credential_deployment_existing,
     &ux_sign_credential_deployment_0_step,
     &ux_sign_credential_deployment_1_step,
     &ux_sign_credential_deployment_2_step
 );
 
+UX_FLOW(ux_sign_credential_deployment_new,
+        &ux_sign_credential_deployment_1_step,
```
Comment (orhoj) [inline src/signCredentialDeployment.c:158]: Align indentation to match what we do elsewhere, i.e. remove one set of spaces.

File: rust_tests/src/bin/credential_deployment.rs (hunk 1 above)
Comment (shjortConcordium) [reply rust_tests/src/bin/credential_deployment.rs:194]: This is the return statement, so data becomes account_address_bytes

File: src/signCredentialDeployment.c (hunk 2 above)
Comment (shjortConcordium) [reply src/signCredentialDeployment.c:32]: Can you end on a NOCB, though? I want to signal after this. We could also just not show this view when updating credentials.

Comment (orhoj) [reply src/signCredentialDeployment.c:32]: As far as I can see you are ending on `ux_update_credentials_initial_flow_1_step` which will do this.

File: rust_tests/src/bin/credential_deployment.rs (hunk 1 above)
Comment (orhoj) [reply rust_tests/src/bin/credential_deployment.rs:194]: Ah, I misread it. Sorry.

File: src/signCredentialDeployment.c (hunk 2 above)
Comment (shjortConcordium) [reply src/signCredentialDeployment.c]: Yes, you are correct. I was confusing this with another component.

**Review by orhoj — APPROVED** [review]
